name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  test-action-01:
    runs-on: ubuntu-latest
    name: GitHub Actions Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          repository: "mauhlik/gopass-store-test"
          private-key: ${{ secrets.INFRASTRUCTURE_GOPASS_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.INFRASTRUCTURE_GOPASS_PRIVATE_KEY_PASSPHRASE }}
          token: ${{ secrets.GOPASS_STORE_CHECKOUT_TOKEN }}

      - name: Assert value
        run: |
          VALUES_FROM_STORE=$(gopass show -o "${STORE_NAME}/.internal/test")
          DESIRED_VALUE="test"
          if [ "$VALUES_FROM_STORE" != "$DESIRED_VALUE" ]; then
            echo "Values from store: $VALUES_FROM_STORE"
            echo "Desired value: $DESIRED_VALUE"
            exit 1
          fi
        env:
          STORE_NAME: ${{ steps.test-action.outputs.store-name }}

  test-action-02:
    runs-on: ubuntu-latest
    name: GitHub Actions Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          repository: "mauhlik/gopass-store-test"
          private-key: ${{ secrets.GOPASS_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.GOPASS_PRIVATE_KEY_PASSPHRASE }}
          store-name: "custom-store-name"
          token: ${{ secrets.GOPASS_STORE_CHECKOUT_TOKEN }}

      - name: Assert value
        run: |
          VALUES_FROM_STORE=$(gopass show -o "${STORE_NAME}/.internal/test")
          DESIRED_VALUE="test"
          if [ "$VALUES_FROM_STORE" != "$DESIRED_VALUE" ]; then
              echo "Values from store: $VALUES_FROM_STORE"
              echo "Desired value: $DESIRED_VALUE"
              exit 1
          fi
        env:
          STORE_NAME: ${{ steps.test-action.outputs.store-name }}

  test-action-03:
    runs-on: ubuntu-latest
    name: GitHub Actions Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          repository: "mauhlik/gopass-store-test"
          private-key: ${{ secrets.GOPASS_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.GOPASS_PRIVATE_KEY_PASSPHRASE }}
          store-name: "gopass-store-test"
          token: ${{ secrets.GOPASS_STORE_CHECKOUT_TOKEN }}

      - name: Assert value
        run: |
          VALUES_FROM_STORE=$(gopass show -o "${STORE_NAME}/.internal/test")
          DESIRED_VALUE="test"
          if [ "$VALUES_FROM_STORE" != "$DESIRED_VALUE" ]; then
            echo "Values from store: $VALUES_FROM_STORE"
            echo "Desired value: $DESIRED_VALUE"
            exit 1
          fi
        env:
          STORE_NAME: ${{ steps.test-action.outputs.store-name }}
