name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action-01:
    runs-on: ubuntu-latest
    name: GitHub Actions Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action-01
        uses: ./
        with:
          repository: "mauhlik/gopass-store-test"
          private-key: ${{ secrets.GOPASS_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.GOPASS_PRIVATE_KEY_PASSPHRASE }}
          token: ${{ secrets.GOPASS_STORE_CHECKOUT_TOKEN }}

  test-action-02:
    runs-on: ubuntu-latest
    name: GitHub Actions Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action-01
        uses: ./
        with:
          repository: "mauhlik/gopass-store-test"
          private-key: ${{ secrets.GOPASS_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.GOPASS_PRIVATE_KEY_PASSPHRASE }}
          store-name: "custom-store-name"
          token: ${{ secrets.GOPASS_STORE_CHECKOUT_TOKEN }}
